language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  include:
    - php: 5.6
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE V2=false
      services:
      - mysql

    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE V2=true
      services:
        - mysql

    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=master V2=true
      services:
        - mysql

    - php: 7.4
      env: DB=pgsql MOODLE_BRANCH=master V2=true
      addons:
        postgresql: 9.5


before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - if [ -n "$GH_TOKEN" ]; then composer config -g github-oauth.github.com ${GH_TOKEN}; fi;
  - if [ "$V2" = false ]; then composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^1; fi
  - if [ "$V2" = true ]; then composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2; fi
  - if [ "$V2" = true ]; then nvm install stable; fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit
